name: Hello

on:
  - workflow_dispatch
 
jobs:
  Hello:
    if: github.event.repository.is_template == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Hello
      run: echo "Hello, GitHub Actions. I am template!"
  Buu:
    needs: Hello
    runs-on: ubuntu-latest
    steps:
    - name: Hu
      run: echo "Buu"
  Message-if-template:
    runs-on: ubuntu-latest
    if: jobs.Buu.result === 'skipped'
    steps:
      - name: print
        run: "Buu is prohibited in the template"
  
