name: Hello

on:
  - workflow_dispatch
 
jobs:
  hello:
    if: $!{{github.event.repository.is_template}}
    runs-on: ubuntu-latest
    
    steps:
    - name: Hello
      run: echo "Hello, GitHub Actions. I am not template!"
  buu:
    needs: hello
    runs-on: ubuntu-latest
    steps:
    - name: Hu
      run: echo "Buu"
  
